services:
  gerev:
    image: us-central1-docker.pkg.dev/gorgias-growth-production/growth-ops:latest
    ports:
      - 80:80
    volumes:
      - ~/.gerev/storage:/opt/storage
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]