"""parnet

Revision ID: 4d9562314bd3
Revises: 513db5127df7
Create Date: 2023-04-07 16:26:31.269456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9562314bd3'
down_revision = '513db5127df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('document', schema=None) as batch_op:
            batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fg_parent_id', 'document', ['parent_id'], ['id'])
    except:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('document', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('parent_id')
    except:
        pass
    # ### end Alembic commands ###
